# YAML
#
# Application: Web service to perform IMDB queries
#
# Purpose: Builds a web stack consisting of multiple containers

version: "3.8"

services:

    # service: frontend (nginx/JS)
    frontend:
        build: ./frontend
        ports:
            - 80:80
        networks:
            - frontnet
        depends_on:
            - backend

    # service: backend (Flask)
    backend:
        container_name: backend
        build: ./backend
        expose:
            - 8000
        networks:
            - backnet
            - frontnet
        links:
            - db
        secrets:
            - db-password
        depends_on:
            db:
                condition: service_healthy
        stdin_open: true # docker run -i
        tty: true        # docker run -t

    # service: db (MySQL)
    db:
        container_name: mysql_db
        build: ./database
        environment:
            - MYSQL_DATABASE=imdb_database
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
            - MYSQL_ROOT_HOST=%
        expose:
            - 3306
            - 33060 
        secrets:
            - db-password
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - backnet
        healthcheck:
            test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="root" --silent']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 60s

volumes:
    db-data:

secrets:
    db-password:
        file: database/password.txt

networks:
  backnet:
  frontnet:
