version: "3"
services:
    db:
        container_name: mydb
        build: ./database
        ports:
            - "3306:3306"
    app:
        container_name: myapp
        links:
            - "db"
        build: ./backend
        ports:
            - "5001:5000"
      